version: '3'
services:
  traefik:
    container_name: traefik
    image: traefik:1.7.12-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ${TRAEFIK_PERSISTENT_ROOT}/acme.json:/acme.json

networks:
  web:
    external: true
